# Generated by Django 4.1.4 on 2022-12-23 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assigned',
            fields=[
                ('Assigned_id', models.AutoField(primary_key=True, serialize=False)),
                ('Course', models.IntegerField(unique=True)),
                ('Student', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('Course_id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=250, unique=True)),
                ('Description', models.TextField(max_length=2000)),
                ('time', models.DateField()),
                ('Author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('Exam_id', models.AutoField(primary_key=True, serialize=False)),
                ('Exam_name', models.CharField(max_length=250, unique=True)),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.course')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('Score_id', models.AutoField(primary_key=True, serialize=False)),
                ('Score', models.IntegerField(unique=True)),
                ('Exam_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.exam')),
                ('Student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('Question_id', models.AutoField(primary_key=True, serialize=False)),
                ('Question', models.TextField(max_length=500, unique=True)),
                ('Option1', models.CharField(max_length=250)),
                ('Option2', models.CharField(max_length=250)),
                ('Option3', models.CharField(max_length=250)),
                ('Option4', models.CharField(max_length=250)),
                ('Correct_Ans', models.CharField(max_length=250)),
                ('Exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.exam')),
            ],
        ),
    ]
